/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Subject.Contraller;

 
/**
 *
 * @author Saluka
 */
public class MainContraller extends javax.swing.JFrame {
  private  Contraller contrall;
    /**
     * Creates new form MainContraller
     */
    public MainContraller(Contraller contrall) {
        initComponents();
        this.contrall = contrall;
        setVisible(true);
    }
    
    public void setMsg(String msg){
        MainMsgBox.setText(msg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        txtsoldiercount = new javax.swing.JLabel();
        txtAmmoAmount = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        Position = new javax.swing.JSlider();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMainmassage = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        MainMsgBox = new javax.swing.JTextArea();
        SelectionDefence = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mainpoto = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setText("                MainContraller");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 6, 337, -1));

        jToggleButton1.setBackground(new java.awt.Color(51, 51, 255));
        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton1.setText(" Collect Information");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        txtsoldiercount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtsoldiercount.setText(" Soldier Count :");
        getContentPane().add(txtsoldiercount, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 88, 121, -1));

        txtAmmoAmount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtAmmoAmount.setText(" Ammo Amount :");
        getContentPane().add(txtAmmoAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 110, 130, -1));

        jProgressBar2.setBackground(new java.awt.Color(102, 255, 0));
        jProgressBar2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jProgressBar2.setForeground(new java.awt.Color(255, 51, 51));
        jProgressBar2.setValue(50);
        jProgressBar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 111, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText(" Positions");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 72, -1));

        Position.setBackground(new java.awt.Color(255, 255, 255));
        Position.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Position.setForeground(new java.awt.Color(51, 51, 51));
        Position.setMajorTickSpacing(10);
        Position.setMinorTickSpacing(5);
        Position.setPaintLabels(true);
        Position.setPaintTicks(true);
        Position.setToolTipText("");
        Position.setValue(0);
        Position.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Position.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                PositionAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Position.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PositionStateChanged(evt);
            }
        });
        Position.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PositionFocusGained(evt);
            }
        });
        getContentPane().add(Position, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 285, -1));

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox1.setText(" Area Cleared");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox2.setText(" Send Private");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 255, 51));
        jButton1.setText(" Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        txtMainmassage.setBackground(new java.awt.Color(204, 204, 204));
        txtMainmassage.setColumns(20);
        txtMainmassage.setRows(5);
        txtMainmassage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane3.setViewportView(txtMainmassage);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 170, 104));

        MainMsgBox.setBackground(new java.awt.Color(204, 204, 204));
        MainMsgBox.setColumns(20);
        MainMsgBox.setRows(5);
        MainMsgBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane4.setViewportView(MainMsgBox);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 172, 107));

        SelectionDefence.setBackground(new java.awt.Color(51, 51, 255));
        SelectionDefence.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SelectionDefence.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Defence", "Helicopter", "Tank", "Submarin", "" }));
        SelectionDefence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectionDefenceActionPerformed(evt);
            }
        });
        getContentPane().add(SelectionDefence, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 48, 152, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Energy");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 110, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Fuel Amount");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 83, -1));

        mainpoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main2.jpg"))); // NOI18N
        mainpoto.setText("jLabel3");
        getContentPane().add(mainpoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PositionAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_PositionAncestorAdded
        
    }//GEN-LAST:event_PositionAncestorAdded

    private void PositionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PositionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_PositionFocusGained

    private void SelectionDefenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectionDefenceActionPerformed
           
        
           
    }//GEN-LAST:event_SelectionDefenceActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
       boolean areastate =(jCheckBox1.isSelected()) ? true : false ;
       contrall.setArea(areastate);
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           String msg = (txtMainmassage.getText());
           contrall.setMsg(msg);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
           
           String item = SelectionDefence.getSelectedItem().toString();
           int[]ar=new int[3];
      switch (item) {
          case "Helicopter":
              ar = contrall.passHelicopterDetails();
              break;
          case "Tank":
              ar= contrall.passTankDetails();
              break;
          case "Submarin":
              ar= contrall.passSubmarinDetails();
              break;
          default:
              break;
      }
        txtAmmoAmount.setText("Ammo Amount   - "+ar[0]);
        txtsoldiercount.setText("Soldier Count - "+ar[1]);
        jLabel4.setText("Energy        - "+ar[2]);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void PositionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PositionStateChanged
        int strength  =Position.getValue();
        contrall.Strenght(strength);
    }//GEN-LAST:event_PositionStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainContraller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainContraller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainContraller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainContraller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea MainMsgBox;
    private javax.swing.JSlider Position;
    private javax.swing.JComboBox<String> SelectionDefence;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel mainpoto;
    private javax.swing.JLabel txtAmmoAmount;
    private javax.swing.JTextArea txtMainmassage;
    private javax.swing.JLabel txtsoldiercount;
    // End of variables declaration//GEN-END:variables

    
     }

   

    
 
